services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped

    environment:
      DJANGO_DEBUG: '${DJANGO_DEBUG:-false}'
      DJANGO_SECRET_KEY: '${DJANGO_SECRET_KEY}'
      DJANGO_ALLOWED_HOSTS: '${DJANGO_ALLOWED_HOSTS}'
      DJANGO_CSRF_TRUSTED_ORIGINS: '${DJANGO_CSRF_TRUSTED_ORIGINS}'

      DATABASE_URL: '${DATABASE_URL}'

      VEGETATION_MODEL_PATH: /app/backend/kbdiproject/model_weights/vegetation_shufflenet_v2_epoch75.pkl

      DJANGO_SECURE_SSL_REDIRECT: '${DJANGO_SECURE_SSL_REDIRECT:-true}'
      DJANGO_SESSION_COOKIE_SECURE: '${DJANGO_SESSION_COOKIE_SECURE:-true}'
      DJANGO_CSRF_COOKIE_SECURE: '${DJANGO_CSRF_COOKIE_SECURE:-true}'
      DJANGO_SECURE_HSTS_SECONDS: '${DJANGO_SECURE_HSTS_SECONDS:-0}'

    expose:
      - '8000'

    volumes:
      - 'media_data:/app/backend/kbdiproject/media'

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile.coolify
    restart: unless-stopped

    depends_on:
      - web

    expose:
      - '80'

    volumes:
      - 'media_data:/media:ro'

volumes:
  media_data: