# Generated by Django 3.2.13 on 2022-05-16 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('peatlandcovers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='peatlandcover',
            name='bare',
        ),
        migrations.RemoveField(
            model_name='peatlandcover',
            name='dense',
        ),
        migrations.RemoveField(
            model_name='peatlandcover',
            name='medium',
        ),
    ]
